name: Hardhat Test & Coverage

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: yarn install --frozen-lockfile
      - name: Run tests with coverage
        run: yarn hardhat coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage.json
          path: coverage.json
